### ISSUE TITLE
Is not fully evaluated on MSVC

### ISSUE THREAD

**Issue by g-berthiaume** [Jorenar/CMObALL#1]
Great work. I really like that it supports empty (0 arg) overload without requiring gcc extension.

That said, the `CMOBAL` macro it doesn't compile on MSVC.

Using the first example in the README, here's the preprocessor `/P` output:

```C
int main()
{
    printf("%d\n", FOO_CMOBALL_ARG_N (,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)());      
    printf("%d\n", FOO_CMOBALL_ARG_N (CMOBALL__DETECT_01_, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)(1));     
    printf("%d\n", FOO_CMOBALL_ARG_N (CMOBALL__DETECT_01,1,1_, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)(1,1,1)); 

    return 0;
}
```

Any idea on making this macro portable across this compiler?

**Comment by Jorenar** [comment]
Hmm, weird... should [work in MSVC](https://c.godbolt.org/z/onqsMoYWP) too.

Have you specified the standard? MSVS defaults to C89 (with some extensions), but it's not enough for CMObALL to work. Since they "skipped" C99, you should specify `/std:c11` at least.

**Comment by g-berthiaume** [comment]
> MSVS defaults to C89

This is news to me. 
I also used godbolt for testing but didn't specify the language version.
My apology for the noise :)

**Comment by Jorenar** [comment]
No problemo!  
My fault for not documenting it in README
